#!/bin/bash
pluginpath="$(dirname "$(readlink -f $0)")"
mkdir -pv "$HOME/.config"
rm -rvf "$HOME/.config/awesome"
ln -svf $pluginpath "$HOME/.config/awesome"
ln -svf $pluginpath/xinitrc "$HOME/.xinitrc"

sudo apt-get install -y awesome xinit
